### PR TITLE
Update repo with upstream changes

### LINKED ISSUE #13968: [HOLD for payment 2023-02-15] [$2000] not able to select text of keyboard shortcuts when you open popup second time
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. open app
2. go to settings > About > View Keyboard shortcuts
3. open  the popup an close it
4. again open the popup and try to select text

## Expected Result:
not able to select text when you open popup second time

## Actual Result:
user should be able to select text

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?

- [ ] MacOS / Chrome 

**Version Number:** 1.2.47-0
**Reproducible in staging?:** y 
**Reproducible in production?:** y
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 

https://user-images.githubusercontent.com/43996225/210454215-e770a2da-afdf-4dbe-ab23-2b6b7e45c4bb.mov

https://user-images.githubusercontent.com/43996225/210454442-330d11d9-8dde-4e24-bdcd-ec5a5c6d5a30.mp4

**Expensify/Expensify Issue URL:**
**Issue reported by:** @gadhiyamanan 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1672381522931449

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0142c09828b956ad3b</li>
        <li>Upwork Job ID: 1613255747122876416</li>
        <li>Last Price Increase: 2023-02-01</li>
    </ul>
</details>

### PR DESCRIPTION
**Pull request by pecanoro**
Just updating this repo from the upstream, and resolving conflicts.

Part of this fix: https://github.com/Expensify/App/issues/13968
Needed to fix this as well: https://github.com/Expensify/App/issues/13871

Preparation to test:
1. Build packages.
2. Drag and drop the packages on the App node-modules to replace the current ones.

Tests:
1. Open the app
2. Go to settings > About > View Keyboard shortcuts
3. Open the popup and close it
4. Again open the popup and try to select text
5. User should be able to select text

### CODE REVIEW

**Review by Beamanator — DISMISSED** [review]
PR looks great, maybe we need to test this in an App PR too?

**Comment by pecanoro** [comment]
Ok, tested it!!! App still runs normally but it does not seem to fix the problem [here](https://github.com/Expensify/App/issues/13968).

**Comment by pecanoro** [comment]
I was holding this wrong and updating the wrong modules in App, the changes actually fix the issue [here](https://github.com/Expensify/App/issues/13968#issuecomment-1412992028).

**Comment by pecanoro** [comment]
I also ran `npm i` that's why the package-lock file also got updated.

**Comment by Beamanator** [comment]
@pecanoro do you mind listing the steps you took to test this? 😅

**Comment by pecanoro** [comment]
Oh sure, I thought linking the original issue with the bug was enough. I added the steps! Sorry about that.

**Review by Beamanator — APPROVED** [review]
Followed the steps, looks like everything is working well! Let's mergeeeee

**Pull request merged**
